name: Run Selenium Tests

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger when a PR is made to the 'main' branch

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set the Java version for your tests

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Install dependencies
        run: mvn install -DskipTests  # Install dependencies (skip tests here to avoid running them twice)

      - name: Run tests
        run: mvn test  # Run your tests

